Develop
next-cesar-school/next20221-m3-melhor-rota pull request #3
Opened 2022-06-13 13:43 UTC by diegolins13

2022-06-13 13:44 UTC, diegolins13 commented
Criação do CRUD

2022-06-14 02:12 UTC, ddspog requested changes

2022-06-14 02:12 UTC, ddspog commented on src/main/java/com/nextm3project/bestRoute/BestRoute.java
> +<<<<<<< HEAD
Essas linhas estranhas são de algum merge que deu errrado. Remover plz.

2022-06-14 02:12 UTC, ddspog commented on src/main/java/com/nextm3project/bestRoute/BestRoute.java
> +>>>>>>> 2da3b60 (Atualização do pom com biblioteca e best route)
Essas linhas estranhas são de algum merge que deu errrado. Remover plz.

2022-06-14 02:12 UTC, ddspog commented on src/main/java/com/nextm3project/bestRoute/BestRoute.java
> +          		        path[i][j] = path[k][j]; // k Ã© a conexÃ£o entre pontos
Checar se a codificação do arquivo tá em UTF-8.

2022-06-14 02:12 UTC, ddspog commented on src/main/java/com/nextm3project/bestRoute/BestRoute.java
> +          		        path[i][j] = path[k][j]; // k Ã© a conexÃ£o entre pontos
![image](https://user-images.githubusercontent.com/5065673/173476216-b5cf5d54-e8e7-4ea5-8cad-7891e275bb29.png)
Se vocês conseguirem ver lá embaixo, no VSCode tem a codificação mostrando como UTF-8. Ao clicar lá dá para trocar para outra codificação. Mas a codificação UTF-8 é a correta, e ideal para usar caracteres de lingua portuguesa como o '˜'.

2022-06-14 02:12 UTC, ddspog commented on src/main/java/com/nextm3project/bestRoute/BestRoute.java
> +          		        path[i][j] = path[k][j]; // k Ã© a conexÃ£o entre pontos
Em Eclipse, vai ser preciso pesquisar por "IDE Eclipse check file encoding"

2022-06-14 02:12 UTC, ddspog commented on src/main/java/com/nextm3project/controllers/TruckController.java
> +    public ResponseEntity<Object> saveTruck(@RequestBody @Valid TruckDto truckDto){		//Método para salvar so dados digitados pelo cliente.
O projeto todo precisa de corrigir identação.

https://stackoverflow.com/questions/15655126/how-to-auto-format-code-in-eclipse
Mas basicamente vocês vão executar Ctrl + Shift + F (Windows and Linux), em todos os arquivos no projeto dentro do Eclipse. E aí salvar e commitar as mudanças.

2022-06-14 02:12 UTC, ddspog commented on src/main/java/com/nextm3project/controllers/TruckController.java
> +    public ResponseEntity<Object> saveTruck(@RequestBody @Valid TruckDto truckDto){		//Método para salvar so dados digitados pelo cliente.
Ajuda muito para outras pessoas revisarem.

2022-06-14 02:12 UTC, ddspog commented on src/main/java/com/nextm3project/controllers/TruckController.java
> +    public ResponseEntity<Object> saveTruck(@RequestBody @Valid TruckDto truckDto){		//Método para salvar so dados digitados pelo cliente.
E claro, vocês mesmo ao olhar código que vocês fizeram dias atrás.

2022-06-14 02:12 UTC, ddspog commented on src/main/java/com/nextm3project/dtos/TruckDto.java
> +	private String status;
Geralmente Status a gente lida com tipo boolean, ou int enum.

Dêem uma olhada aqui: https://www.baeldung.com/a-guide-to-java-enums
Aqui tem um guia de como criar uma classe enum e utilizá-la.

2022-06-14 02:12 UTC, ddspog commented on src/main/java/com/nextm3project/dtos/TruckDto.java
> +package com.nextm3project.dtos;
Eu colocaria dentro do package models. Como o projeto é pequeno preferiria ter menos packages.

2022-06-14 14:08 UTC, ddspog commented on src/main/java/com/nextm3project/bestRoute/BestRoute.java
> +          		        path[i][j] = path[k][j]; // k Ã© a conexÃ£o entre pontos
https://logic.edchen.org/how-to-change-file-encoding-in-eclipse/

2022-06-17 13:05 UTC, merged